remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Ryan Knauer
description: Online CV for Ryan Knauer
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  owner_url: https://github.com/bagel-dawg
  is_user_page: true
  is_project_page: false
  zip_url: https://github.com/bagel-dawg/bageltech-io/releases/latest
  tar_url: https://github.com/bagel-dawg/bageltech.io/tree/main/src/bageltech-io
  repository_url: https://github.com/bagel-dawg/bageltech.io/tree/main/src/bageltech-io
