on:
  push: 
  pull_request:
    types: [opened, synchronize]
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    name: Jekyll Build
    defaults:
      run:
        working-directory: src/bageltech-io
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Gem Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Generate site
        run: |
          bundle exec jekyll build 

      - name: Test site for valid HTML
        run: |
          bundle exec htmlproofer ./_site --check-html --check-sri

      - name: Configure AWS credentials
        if: github.event_name == 'release'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::204361647268:role/bageltech-io-cicd
          aws-region: us-east-1

      - name: Publish to bageltech.io bucket
        if: github.event_name == 'release'
        run: | 
          aws --region us-east-1 s3 sync src/bageltech-io/_site s3://bageltech.io --delete